apiVersion: v1
kind: Service
metadata:
  name: beetroot-service
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: beetroot
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8080

