apiVersion: v1
kind: Service
metadata:
  name: apache-proxy-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: apache-proxy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Optional, you can let Kubernetes allocate this port automatically.
